### ISSUE TITLE
Represent Kubernetes values.yaml schema as cue data

### ISSUE THREAD

**Issue by spencergilbert** [timberio/helm-charts#13]
@binarylogic commented on [Sun Nov 15 2020](https://github.com/timberio/vector/issues/5036)

As part of documenting Kubernetes, we need to expose the various fields allowed in the `values.yml`. This should be encoded in our cue data in the same way that our components document their `configuration`.

---

@MOZGIII commented on [Fri Nov 27 2020](https://github.com/timberio/vector/issues/5036#issuecomment-734685052)

Helm supports `values.schema.json` now: https://helm.sh/docs/topics/charts/
I think we should focus on that instead first, and then use the JSON Schama in .cue files to extract the data. It should be possible to do. I created an issue #5253.

---

@binarylogic commented on [Fri May 14 2021](https://github.com/timberio/vector/issues/5036#issuecomment-841480145)

See https://github.com/timberio/vector/issues/5253#issuecomment-841477489

**Comment by binarylogic** [comment]
Just noting here, that we might need to do this. It really comes down to best practices for Helm documentation. If users are used to reviewing the `values.yml` file, then we don't need to create external docs for this. We can just link to the `values.yml` file and add quality comments.

**Comment by spencergilbert** [comment]
There was some discussion around this recently with @lucperkins - I'm open to whatever makes sense for us and the docs team

**Comment by binarylogic** [comment]
Well, as the owner of the Helm UX, what would provide the best experience? Would Helm users prefer a well commented values.yml or separate docs?

**Comment by spencergilbert** [comment]
I think community expectations lean towards commented `values.yaml` and the `README.md` files. I can't think of anything substantially better we could provide by rendering cue data on the website.

There would be some value from being able to derive a json schema from the cue data, but since that's not yet supported we'd be just as well off writing the json schema ourselves.

I'm comfortable closing this and polishing the documentation in this repo as-is.

**Comment by binarylogic** [comment]
Sounds good. Works for me.
