### ISSUE TITLE
Setup semantic PR's/commits

### ISSUE THREAD

**Issue by spencergilbert** [timberio/helm-charts#39]

**Comment by spencergilbert** [comment]
It seems the easiest way to do this with atomic PRs and `cr` is having a *release* branch that `cr` packages off of, and we merge *main*/*master* into it whenever we want to release. Thoughts @jszwedko?

**Comment by jszwedko** [comment]
Yeah, I think that sounds like a reasonable workflow. We should just make sure to document it in the README.

**Comment by spencergilbert** [comment]
> Yeah, I think that sounds like a reasonable workflow. We should just make sure to document it in the README.

Definitely, I'll open a PR for this later today/this weekend

**Comment by spencergilbert** [comment]
Actually thinking about this... might need to adjust some of the `ct` config to compare properly so we're not still forced to increment the chart version on every PR

**Comment by spencergilbert** [comment]
It seems like the simplest answer is actually adding a `develop` branch as the default branch between `master` and _features_, which avoids needing to update any of the CI config
